---
- name: Minimal server setup
  hosts: all
  become: true
  pre_tasks:
  
  - name: Update and upgrade
    tags: update,upgrade
    apt:
      update_cache: yes
      upgrade: dist

- name: Manage Ansible user account
  hosts: base
  become: true
  tags: base
  roles:
  - base

- name: Set up Nginx webserver with SSL cert (certbot)
  hosts: web
  become: true
  tags: web
  roles:
  - web

- name: Set up mail-server
  hosts: mail
  become: true
  tags: mail
  roles:
  - mail


